// auth
// export const AUTH_XXX = 'AUTH_XXX';

// product
export const PRODUCT_ADD = 'PRODUCT_ADD';
export const PRODUCT_DELETE = 'PRODUCT_DELETE';

// new
export const SELECT_PRODUCT = 'SELECT_PRODUCT';
export const SUBMIT_PRODUCT = 'SUBMIT_PRODUCT';
export const FETCH_PRODUCTS_REQUEST = 'FETCH_PRODUCTS_REQUEST';
export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';